# Generated by Django 2.0 on 2017-12-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awardnominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=20)),
                ('nominee_description', models.TextField()),
                ('nominee_image_name', models.CharField(max_length=20)),
                ('num_votes', models.SmallIntegerField()),
            ],
        ),
    ]
