# Generated by Django 2.0 on 2017-12-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='meals',
            field=models.CharField(blank=True, choices=[('mealpack', 'Dinner Both Days'), ('dinnerday2', 'Day 2 Dinner Only')], max_length=15, null=True),
        ),
    ]
